[versions]
activity = "1.9.0"
agp = "8.5.0"
appcompat = "1.7.0"
coil = "2.6.0"
compose-bom = "2024.06.00-alpha01"
core-ktx = "1.13.1"
koin = "3.5.6"
kotlin = "2.0.0"
kotlinx-serialization-json = "1.7.3"
ksp = "2.0.0-1.0.22"
landscapist = "2.3.6"
lifecycle = "2.8.3"
material = "1.12.0"
material3 = "1.2.1"
navigation-compose = "2.7.7"
orbit = "9.0.0"
paging = "3.2.1"
room = "2.6.1"
work-runtime = "2.9.0"
yuki = "1.2.1"

[libraries]
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "compose-bom" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
landscapist-coil = { module = "com.github.skydoves:landscapist-coil", version.ref = "landscapist" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
multidex = { module = "androidx.multidex:multidex", version = "2.0.1" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }
orbit-core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbit" }
orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
runtime = { module = "androidx.compose.runtime:runtime" }
startup = { module = "androidx.startup:startup-runtime", version = "1.1.1" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "work-runtime" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime" }
xposed-api = { module = "de.robv.android.xposed:api", version = "82" }
yukihook-api = { module = "com.highcapable.yukihookapi:api", version.ref = "yuki" }
yukihook-ksp = { module = "com.highcapable.yukihookapi:ksp-xposed", version.ref = "yuki" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jgit = { id = "org.lsposed.lsplugin.jgit", version = "1.1" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
